### ISSUE TITLE
"Update program" may consider a merge

### ISSUE THREAD

**Issue by nunziofiore** [CoderBotOrg/coderbot#39]
Befor git pull on AGGIORNAMENTO you have to consider a merge, because you have this situation after a while:

```
pi@coderbot ~/coderbot $ git status
   On branch master
   Your branch is ahead of 'origin/master' by 12 commits.

  Changes not staged for commit:
    (use "git add/rm <file>..." to update what will be committed)
    (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   coderbot.cfg
    deleted:    data/program_.data
    modified:   data/program_no_name.data
```

and your pull could be refused

**Comment by previ** [comment]
We are redesigning the full update process:
- firmware will be updated transactionally, uploading a package via web interface
- user programs and setting will be preserved and, if necessary, upgraded
