### ISSUE TITLE
Which version to use with Beaglebone???

### ISSUE THREAD

**Issue by hohae** [CoderBotOrg/coderbot#43]
uname -a returns:

Linux beaglebone 4.1.15-ti-rt-r40 #1 SMP PREEMPT RT Thu Jan 7 23:32:08 UTC 2016 armv7l GNU/Linux

**Comment by previ** [comment]
I do not really know: I only tested on Raspbian (wheezy), not sure if it can run on Beaglebone; definitely interesting, by the way.

**Comment by hohae** [comment]
Hi!

No, it does not work. I get the following error:

insmod: ERROR: could not insert module /lib/modules/4.1.15-ti-rt-r40/kernel/drivers/net/wireless/8188eu.ko: Invalid module format

Anything else I could try? Would be happy to get my dongle to run as WIFI access point.

Regards,
Holger

**Comment by previ** [comment]
I guess the 8188eu.ko is not compatible with the Beaglebone linux kernel.
Is it compiled from this source?
https://github.com/beagleboard/linux/tree/36f538b563fbde1279aecbcf035635d5d1e10c4e/drivers/staging/rtl8188eu
You may wish to open a request on the Linux beaglebone repository.

**Comment by hohae** [comment]
No, i just took the tar.gz.

What do I need to compile? Just download and run make?

**Comment by previ** [comment]
Sorry, I don't really know.
