### ISSUE TITLE
print blocks is broken (no longer superimpose text on video image)

### ISSUE THREAD

**Issue by previ** [CoderBotOrg/coderbot#54]
It was nice to be able to print text on the streamed images (for example: distance to objects, etc.).
It would be also nice to be able to have a "console log" on the UI (as a separate, optional, window,)

**Comment by deveil** [comment]
Yes the printed text is in my mind. Not all block's generated code is written.
I want to add the possibility to add text and more (draw line/rectangle/circle).
I just haven't time to add this yet :p
This is in the TODO list.

The console is a good idea too. I get it in mind and add this in the TODO list.
